//#pragma once
//
//remove dev paths C:\jsons/fonts/etc
//USE THE PATH SYTEM THAT DIALOGUE MANAGER USES FOR OTHER PATHS
//ADD LIGHTING TO LEVEL LOADER
//TEST JSON FOR LIGHTING AND AMBIANCE
//ADD LIGHTING AND AMBIANCE MANAGER TO EVENT SYSTEM
//ADD LIGHTNING SPAWNING FOR SPECIFIED RECT ONLY
//TINT ISN'T JSON"D IN AMBIANCE
//MAKE SURE CAN SERIALIZE ALL EFFECTS FOR SAVE/LOAD(LIGHTNING NOT FINISHED)/UPDATE LIGHTNINGSTORMS PTR MEMBER FOR DEF TO VALUE NOT PTR)