//#pragma once
//
//remove dev paths C:\jsons/fonts/etc
//USE THE PATH SYTEM THAT DIALOGUE MANAGER USES FOR OTHER PATHS
//ADD LIGHTING TO LEVEL LOADER
//TEST JSON FOR LIGHTING AND AMBIANCE
//ADD LIGHTING AND AMBIANCE MANAGER TO EVENT SYSTEM