//#pragma once
//
//remove dev paths C:\jsons/fonts/etc
//USE THE PATH SYTEM THAT DIALOGUE MANAGER USES FOR OTHER PATHS
//ADD LIGHTING TO LEVEL LOADER
//TEST JSON FOR LIGHTING AND AMBIANCE
//ADD LIGHTING AND AMBIANCE MANAGER TO EVENT SYSTEM
//ADD LIGHTNING SPAWNING FOR SPECIFIED RECT ONLY
//TINT ISN'T JSON"D IN AMBIANCE
//MAKE SURE CAN SERIALIZE ALL EFFECTS FOR SAVE/LOAD(LIGHTNING NOT FINISHED)/UPDATE LIGHTNINGSTORMS PTR MEMBER FOR DEF TO VALUE NOT PTR)
//FIX JSON FOR AMBIANCE MANAGER
//UPPDATE EFFECTS TO USE SDL_COLOR_RANGE.h 
//check all places ambiance was used i cant remember where but something wasnt being used right(i think rendering)

//move degToRad() out of randomUtilityFunctions.h
//update linebatch to be like particlebatch(resizing, dont use pushback [i]instead, sort by color)
//test particle animation per particle instead of storm time 
//WHEN RAINSTORM ENDS THE DROPS DISAPEAR BUT WE SHOULD TAPER OFF OR JUST STOP SPAWNING, NOT STOP SPAWNING AND REMOVE DROPS BEFORE THEY GET TO BOTTOM OF SCREEN
//^^PERHAPS AN EMIT TIME THAT IS ALWAYS A FEW SECONDS SHORTER THAN THE AGE OF THE STORM 

//TEST OVEWRRIDE PARAMS FOR PARTICCLE/RAIN/ETC ALSO UPDATE FIRE AND LIGHTNING TO WORK LIKE PARTICLE AND RAIN

//    if (s.actualKillParams.rect.w > 1800) { s.actualKillParams.rect.w = 1800; } < NEED TOFIGURE OUT REFERENCE TO SIZE INSTEAD OF PURE #